steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/exam-registration-app-cicd/exam-app/exam-app', '.']

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/exam-registration-app-cicd/exam-app/exam-app']

  # Step 3: Run basic tests (we'll create a test file next)
  - name: 'python'
    entrypoint: 'python3'
    args: ['-m', 'unittest', 'discover', '-s', 'tests']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'exam-app',
        '--image', 'us-central1-docker.pkg.dev/exam-registration-app-cicd/exam-app/exam-app',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated'
      ]

images:
  - 'us-central1-docker.pkg.dev/exam-registration-app-cicd/exam-app/exam-app'
